### ISSUE TITLE
Canvas is not working

### ISSUE THREAD

**Issue by GoldenEagle1527** [TKoestlerx/sdexperiments#4] opened 2022-10-29 12:43 UTC
I imported the image with the canvas open, but I couldn't drag the thumbnail image to img2img, and the button to grab the result didn't work.
![image](https://user-images.githubusercontent.com/102948742/198832262-b7c7b237-0c50-4fb2-afe8-cccadad6a0b7.png)
I'm using Google Chrome and it reported these errors when I dragged images to img2img.
![image](https://user-images.githubusercontent.com/102948742/198832085-02b562dc-55e1-4c7b-ac95-9f48037ce9e4.png)
![image](https://user-images.githubusercontent.com/102948742/198832113-27791629-4f05-49c0-83cc-b999e0280dab.png)
![image](https://user-images.githubusercontent.com/102948742/198832161-fe9dd23c-c364-4942-bebf-4c6c7b59a079.png)
When I hit the grab results button, the console didn't respond.

**Comment by TKoestlerx** [comment] 2022-10-29 18:26
I have seen this bug pop up a few times during development. It always appeared when I broke something in the gradio html structures.
But I don't know that it triggers it in this case.

You could try to save the thumbnail with a rightclick and load it normally into the src window.  But then you probably cant get it back into the canvas. (If you drag the thumbnail to the src window it stores it original position so it can be copied back).

Maybe there is a better way to transfer the image to the gradio client.

**Comment by Axolotron** [comment] 2022-10-30 08:07
Same issue under Firefox. I'm using Automatic1111 ui with a colab.

**Comment by TKoestlerx** [comment] 2022-10-31 05:12
I use the automatic1111 webui only locally and do not know if adjustments are necessary for the colab variant.
Technically the drag and drop element is actually a simple html img element with the image data of the selected region.
There is not too much I can do at this point.

The older variant of the script ( branch: windowedcanvas) uses directly the SrcImage from the img2img tab and passes only the X/Y coordinates of the region to gradio. But this version does not include inpainting of larger images.

**Comment by TKoestlerx** [comment] 2022-10-31 06:49
And drag and drop doesn't seem to work in firefox even with the images generated by gradio itself.
It seems that I have to add special "send to" buttons to transfer the image data.

**Comment by TKoestlerx** [comment] 2022-10-31 11:16
I have changed the image transfer.
Now clicking on the image will transfer it to the gradio interface.
This should work in Firefox too.

**Comment by sygi** [comment] 2022-10-31 22:01
Just tested it, but the issue still prevails.

https://user-images.githubusercontent.com/495380/199118741-ed52725f-f798-4e21-8183-86e748a8cd1d.mp4

**Comment by sygi** [comment] 2022-10-31 22:19
I also tested firefox, but there even moving the thumbnail from big canvas doesn't work for me.

**Comment by TKoestlerx** [comment] 2022-11-01 09:59
drag and drop is completely removed as it never worked properly in firefox.

A click on the thumbnail icon in the upper left corner of the canvas window is enough to transfer the image to the gradio interface.

The thumbnails on the right side copy themselves (when clicked) on the red marked area in the canvas (I just added this marking to make the procedure a bit more transparent).

**Comment by GoldenEagle1527** [comment] 2022-11-01 11:07
A new problem, Google browser does not respond to click on crawl, will not crawl and display thumbnails.When I chose to drag the result directly into the canvas, the browser reported an error.
[20221101190346.webm](https://user-images.githubusercontent.com/102948742/199219827-a7139a22-1dab-4b77-99ce-9beed644eb08.webm)

**Comment by TKoestlerx** [comment] 2022-11-01 11:27
I think the Problem may be that these are linked as filesystem references.
This is how the script locates the result Images:
![nonlocal](https://user-images.githubusercontent.com/86352149/199222707-5d7607e5-8479-4c81-ad75-ecf0b9ccafa5.jpg)

From that point i just take this .src and use it to create the thumbnails on the right side.

**Comment by TKoestlerx** [comment] 2022-11-01 11:53
I have added an explicit conversion to base64 for the grabbed Images.

This *may* solve your Problem.

**Comment by GoldenEagle1527** [comment] 2022-11-01 12:26
> 我已经为抓取的图像添加了到 base64 的显式转换。
> 
> _这可能会_解决您的问题。
That didn't work. I switched to the Edge browser and got the same result

**Comment by GoldenEagle1527** [comment] 2022-11-01 12:30
> 我已经为抓取的图像添加了到 base64 的显式转换。
> 
> _这可能会_解决您的问题。
Maybe it's the wrong class name?
![image](https://user-images.githubusercontent.com/102948742/199232528-898a25d9-13ab-4644-b2de-826e195ef288.png)
![image](https://user-images.githubusercontent.com/102948742/199232622-b073ea49-bc50-4d99-9af6-4d3a534d78ab.png)

**Comment by GoldenEagle1527** [comment] 2022-11-01 12:33
> > 我已经为抓取的图像添加了到 base64 的显式转换。
> > _这可能会_解决您的问题。也许是错误的类名？
> > ![image](https://user-images.githubusercontent.com/102948742/199232528-898a25d9-13ab-4644-b2de-826e195ef288.png)
> > ![image](https://user-images.githubusercontent.com/102948742/199232622-b073ea49-bc50-4d99-9af6-4d3a534d78ab.png)
It looks something like this
![image](https://user-images.githubusercontent.com/102948742/199233269-53a913d0-8639-41ca-aadf-a606e2244d56.png)

**Comment by TKoestlerx** [comment] 2022-11-01 14:17
They are existing twice, but with the same data format.

I have added some debug Lines to the code.

**Comment by sygi** [comment] 2022-11-01 20:42
I can confirm that the outpainting now works. However, the inpainting seems to be broken: the images taken from canvas don't seem to react to the mask drawn on top of them: however big the drawn mask is, the final result behaves as if there was no mask. This doesn't happen outside of the AlphaCanvas.

https://user-images.githubusercontent.com/495380/199336946-493554ed-5108-4dfb-a4f9-a51b20dd978c.mp4

Note that I chose 0 denoising strength, which means that the masked area should be covered with the latent noise.

**Comment by sygi** [comment] 2022-11-01 20:46
Weirdly, I found that changing script to None (from AlphaCanvas) helps to fix it, even without closing the actual canvas

**Comment by TKoestlerx** [comment] 2022-11-01 21:08
Yes, 
Unfortunately, the script must be on for outpainting, but it must not be on for inpainting. Since img2img and img2img inpainting currently share the same script slot, I can't easily change that either.

**Comment by StewieGriffin** [comment] 2022-11-01 23:57
First, congrats @TKoestlerx on this usefull script

I can confirm outpainting now works fine, clicking the thumbnail sends the image to the interface. Nice one!

PS: using Firefox

**Comment by GoldenEagle1527** [comment] 2022-11-02 10:42
> First, congrats @TKoestlerx on this usefull script
> 
> I can confirm outpainting now works fine, clicking the thumbnail sends the image to the interface. Nice one!
> 
> PS: using Firefox
Unfortunately, I used Firefox, but got the same result, again invalid, and the console said no images were found
![image](https://user-images.githubusercontent.com/102948742/199469457-a39c1345-4489-4392-8802-eef77d6f2999.png)

**Comment by TKoestlerx** [comment] 2022-11-02 11:22
Thats this part of the debug code i have added:
                    let imgParent = gradioApp().getElementById('img2img_gallery');
                    const choices = imgParent.getElementsByClassName('gallery-item group');
                    let nr = 0;
                    alphaSideMenu.innerHTML = '';
                    console.info('reading results... checking ' + choices.length + ' elements.');

You can enter the first two lines directly into the browser console. choices should contain the collected (found) image Elements at this point. 

![console2](https://user-images.githubusercontent.com/86352149/199477269-eaaf349a-1d82-4a9c-a0de-2d3d897e350a.jpg)

You can maybe try the different classNames you mentioned, and see if you can get this array filled.

**Comment by TKoestlerx** [comment] 2022-11-02 11:25
And it should now be possible to leave the script active, even when in inpainting mode.
And outpainting should be possible in the inpainting tab. ( the script will upload a mask too).

**Comment by GoldenEagle1527** [comment] 2022-11-02 11:51
> Thats this part of the debug code i have added: let imgParent = gradioApp().getElementById('img2img_gallery'); const choices = imgParent.getElementsByClassName('gallery-item group'); let nr = 0; alphaSideMenu.innerHTML = ''; console.info('reading results... checking ' + choices.length + ' elements.');
> 
> You can enter the first two lines directly into the browser console. choices should contain the collected (found) image Elements at this point.
> 
> ![console2](https://user-images.githubusercontent.com/86352149/199477269-eaaf349a-1d82-4a9c-a0de-2d3d897e350a.jpg)
> 
> You can maybe try the different classNames you mentioned, and see if you can get this array filled.
As I said yesterday, I got it after changing the class name to the one I took a screenshot of yesterday. For some reason, am I the only one whose code is different from everyone else's?
![image](https://user-images.githubusercontent.com/102948742/199482623-07a53dc7-959b-445e-b238-108d7e553b06.png)

**Comment by TKoestlerx** [comment] 2022-11-02 12:01
Thats ... weird.
Maybe some options in the webui alter the way the files are shown in the page?

Thanks for helping to find this issue.

**Closed as completed** 2022-11-03 13:48 UTC
